---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengzhu.
--- DateTime: 2023/3/8 16:16
---


---更新点赞状态
if (redis.call('hexists', KEYS[1], KEYS[2]) == 1) then
    --当前的点赞状态
    -- 这里是个坑 ARGV[1]是字符串！！！！
    if (tonumber(ARGV[1]) == 1) then
        redis.call('hset', KEYS[1], KEYS[2], 0);
    else
        redis.call('hset', KEYS[1], KEYS[2], 1);
    end
else
    --不存在点赞关系 set值默认为1已点赞
    redis.call('hset', KEYS[1], KEYS[2], 1);
end ;

--- 更新点赞数量
if (redis.call('hexists', KEYS[3], KEYS[4]) == 1) then
    --当前的点赞状态
    -- 这里是个坑 ARGV[1]是字符串！！！！
    if (tonumber(ARGV[1]) == 1) then
        --取消点赞的情况
        redis.call('hincrby', KEYS[3], KEYS[4], -1);
    else
        --点赞的情况
        redis.call('hincrby', KEYS[3], KEYS[4], 1);
    end
else
    --不存在点赞数 set值默认为1
    redis.call('hset', KEYS[3], KEYS[4], 1);
end ;
