---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengzhu.
--- DateTime: 2023/3/22 21:22
---


---更新关注状态
if (redis.call('hexists', KEYS[1], KEYS[2]) == 1) then
    --当前的关注状态
    local state = redis.call('hget', KEYS[1], KEYS[2]);
    if (tonumber(state) == 1) then
        redis.call('hset', KEYS[1], KEYS[2], 0);
    else
        redis.call('hset', KEYS[1], KEYS[2], 1);
    end
else
    --不存在关注关系 set值默认为1已关注
    redis.call('hset', KEYS[1], KEYS[2], 1);
end ;

--- 更新关注数量
if (redis.call('hexists', KEYS[3], KEYS[4]) == 1) then
    --执行状态更新后的关注状态
    local state = redis.call('hget', KEYS[1], KEYS[2]);
    if (tonumber(state) == 0) then
        --取消关注的情况
        redis.call('hincrby', KEYS[3], KEYS[4], -1);
    else
        --关注的情况
        redis.call('hincrby', KEYS[3], KEYS[4], 1);
    end
else
    --不存在关注数 set值默认为1
    redis.call('hset', KEYS[3], KEYS[4], 1);
end ;

--- 更新粉丝数量
if (redis.call('hexists', KEYS[5], KEYS[6]) == 1) then
    --执行状态更新后的关注状态
    local state = redis.call('hget', KEYS[1], KEYS[2]);
    if (tonumber(state) == 0) then
        --取消关注的情况
        redis.call('hincrby', KEYS[5], KEYS[6], -1);
    else
        --关注的情况
        redis.call('hincrby', KEYS[5], KEYS[6], 1);
    end
else
    --不存在粉丝数 set值默认为1
    redis.call('hset', KEYS[5], KEYS[6], 1);
end ;
